name: CI

on:
  workflow_dispatch

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      VERBOSE: 0
      GOFLAGS: -mod=readonly

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Coverage
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

      - name: Check Test Coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: cover.out
          threshold-file: 60
          threshold-package: 60
          threshold-total: 60

